version: '3.7'
services:
  bookstore-api:
    build: .
    image: bookstore-image:0.1
    depends_on:
      - bookstore_db_uat
    ports:
      - "8090:8083"
    volumes:
      - ./uploads:/tmp/uploads
    user: ${UID}
    environment:
      - SPRING_PROFILES_ACTIVE=uat
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookstore_db_uat:5432/postgres
    networks:
      - bookstore-net
    command: ["java","-jar","test-0.0.1-SNAPSHOT.jar"]
    ## OVERIDE VIA COMMAND LINE
    # command: ["java","-jar","test-0.0.1-SNAPSHOT.jar","--spring.profiles.active=uat","--spring.datasource.url=jdbc:postgresql://bookstore_db_uat:5432/postgres","--spring.datasource.password=654321"]

  bookstore_db_dev:
    image: postgres:12
    ports:
      - "1222:5432"
    user: ${UID}
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456
    networks:
      - bookstore-net

  bookstore_db_uat:
    image: postgres:12
    ports:
        - "1333:5432"
    user: ${UID}
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 654321
    networks:
        - bookstore-net

# volumes:
#   m2-cache:
#   postgresql-volume2:
#     external: true
networks:
  bookstore-net:
    external: true
